export const SELECT_OBJECT = 'SELECT_OBJECT';
export const DELETE_OBJECT = 'DELETE_OBJECT';
export const SET_OBJECT = 'SET_OBJECT';
export const CREATE_OBJECT = 'CREATE_OBJECT';
export const EDIT_DURATION = 'EDIT_DURATION';
export const ADD_EFFECT = 'ADD_EFFECT';
export const DELETE_EFFECT = 'DELETE_EFFECT';
export const ADD_EFFECT_STACK = 'ADD_EFFECT_STACK';
export const DELETE_EFFECT_STACK = 'DELETE_EFFECT_STACK';
export const SET_EFFECT_STACK = 'SET_EFFECT_STACK';
export const IMPORT_EFFECT_BP = 'IMPORT_EFFECT_BP';
export const IMPORT_OBJECT_BP = 'IMPORT_OBJECT_BP';

export const ACTION_PAUSE = "ACTION_PAUSE";
export const ACTION_PLAYPAUSERESUME = "ACTION_PLAYPAUSERESUME";
export const ACTION_STOP = "ACTION_STOP";
export const ACTION_RESUME = "ACTION_RESUME";
export const ACTION_REACH_TIME = "ACTION_REACH_TIME";

export const EDIT_EFFECT_STACK = 'EDIT_EFFECT_STACK';
export const EDIT_ATTRIBUTE = 'EDIT_ATTRIBUTE';
export const IMPORT_BLUEPRINT = 'IMPORT_BLUEPRINT';
export const IMPORT_EFFECT = 'IMPORT_EFFECT';

export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';

export const SHOW_MORE_OBJECTS = 'SHOW_MORE_OBJECTS';
export const SHOW_EFFECTS = 'SHOW_EFFECTS';
export const EMPTY_SELECTION = 'EMPTY_SELECTION';

export const TOGGLE_EFFECT_BPS = 'TOGGLE_EFFECT_BPS';
export const TOGGLE_OBJ_BPS = 'TOGGLE_OBJ_BPS';
export const PLAYING = 'PLAYING';