export const ADD_OBJECT = 'ADD_OBJECT';
export const DELETE_OBJECT = 'DELETE_OBJECT';

export const ADD_EFFECT = 'ADD_EFFECT';
export const DELETE_EFFECT = 'DELETE_EFFECT';

export const ADD_EFFECT_STACK = 'ADD_EFFECT_STACK';
export const EDIT_EFFECT_STACK = 'EDIT_EFFECT_STACK';
export const DELETE_EFFECT_STACK = 'DELETE_EFFECT_STACK';

export const SELECT_OBJECT = 'SELECT_OBJECT';
export const EDIT_ATTRIBUTE = 'EDIT_ATTRIBUTE';
export const IMPORT_BLUEPRINT = 'IMPORT_BLUEPRINT';
export const IMPORT_EFFECT = 'IMPORT_EFFECT';

export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';


